### ISSUE TITLE
Using trained model to create a prediction

### ISSUE THREAD

**Issue by simonloeffler** [DeepSceneSeg/AdapNet-pp#22]
Hello,

first of all I want to say that I really like your work (the implementation and the AdapNet paper). I am trying to use it for a project and trained a model on my own dataset. Training an evaluation are working fine (as far as i can tell at the moment) but i would like to use the model for some predictions, just like the examples in the readme (image folder) but only in grayscale (same format as used for the creation of the .tfrecords dataset). Unfortunately it seems like there is no possibility to do this with the code from the repository, or maybe it is possible, but I just missed something. I tried to get the predictions from the evaluation script but this did not quite work out. So I wanted to ask how you got the predictions from the trained model, maybe it would even be possible for you to share the code.

Thank you very much :)

**Comment by mohan1914** [comment]
The provided code doesn't have any method for saving the predictions. After ln 58, the prediction will be of the shape BxHxW, loop through along B and save the predictions. For eg in case of using opencv

for i in range(prediction.shape[0]):
    cv2.imwrite(save_path, np.uint8(prediction[i]))  
It should work. Otherwise, you can send me the script that you are using for saving the images. I can look into it.

**Comment by simonloeffler** [comment]
This works great, thank you very much!
