### ISSUE TITLE
can you provide the cityscape checkpoint

### ISSUE THREAD

**Issue by coldsheephot** [DeepSceneSeg/AdapNet-pp#9]
Cityscapes (void + 11 classes)
Modality | mIoU
-- | --
RGB | 80.77
Depth | 65.01
HHA | 67.63

-------------------------

I cannot to load the checkpoint of the RGB model,I use the path in config(checkpoint)

 Key resnet_v2_50/beta1_power not found in checkpoint

**Comment by avalada** [comment]
From Not found: Key resnet_v2_50/beta1_power I can infer you are not talking about evaluate.py script which does the evaluation. You are most likely running the train.py with checkpoint as our model that we provide and hence the error.

If you want to perform evaluation use the evaluation script or if you want to train the model from our pre-trained checkpoint you should add its path to
'initialize:' rather than 'checkpoint:' param.

**Comment by coldsheephot** [comment]
the num_classes=12, the checkpoint is the RGB model:
when I use the checkpoint to  evalute:
8.62191438941 total_data:  500

why it is so low? -->I think it is not the finally model

------------

when I train it ,use the intialize, the has the error:

ValueError: No variables to save

**Comment by avalada** [comment]
You are probably doing something wrong with the preprocessing. Either with mapping the class labels or something else.

The miou for the checkpoint is 80.77.
